version: "3.8"

services:
   
   mysql:
      user: "${UID}:${GID}"
      image: mysql
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: devops
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
      volumes:
        - ./mysql-data:/var/lib/mysql
        - ./message.sql:/docker-entrypoint-initdb.d/message.sql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 60s


   flask-app:
       build:
         context: .
       container_name: flask-app
       ports:
         - "5001:5000"
       environment:
         MYSQL_HOST: mysql
         MYSQL_USER: root
         MYSQL_PASSWORD: root
         MYSQL_DB: devops
       depends_on:
          - mysql
       restart: always
       healthcheck:
         test: ["CMD-SHELL", "curl -h localhost:5000/health || exit 1"]
         interval: 10s
         retries: 5
         timeout: 5s
         start_period: 60s
